spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://192.168.1.9:3306/mybatis_auto_inject?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&nullCatalogMeansCurrent=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Meefo.cn@123
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
  tomcat:
    max-connections: 30000
  servlet:
    context-path: /mybatisAutoInject
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


